/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import java.awt.Color;

/**
 *
 * @author alumnadotarde
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form PantallaPrincipal
     */
    public PantallaPrincipal() {
        initComponents();
        getContentPane().setBackground(Color.pink);
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelBienvenida = new javax.swing.JLabel();
        jLabelBienvenida1 = new javax.swing.JLabel();
        jLabelBienvenida2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPerros = new javax.swing.JMenu();
        jMenuItemPerrosVer = new javax.swing.JMenuItem();
        jMenuItemPerrosAdoptar = new javax.swing.JMenuItem();
        jMenuItemPerrosDarAdopcion = new javax.swing.JMenuItem();
        jMenuGatos = new javax.swing.JMenu();
        jMenuItemGatosVer = new javax.swing.JMenuItem();
        jMenuItemGatosAdoptar = new javax.swing.JMenuItem();
        jMenuItemDarAdopcion = new javax.swing.JMenuItem();
        jMenuCuenta = new javax.swing.JMenu();
        jMenuItemCuentaDatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelBienvenida.setFont(new java.awt.Font("Mallanna", 0, 36)); // NOI18N
        jLabelBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBienvenida.setText("a");

        jLabelBienvenida1.setFont(new java.awt.Font("Mallanna", 0, 36)); // NOI18N
        jLabelBienvenida1.setText("El Bosque");

        jLabelBienvenida2.setFont(new java.awt.Font("Mallanna", 0, 36)); // NOI18N
        jLabelBienvenida2.setText("Bienvenido/a");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("¿Ya tienes una cuenta?");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("¿Quieres registrarte?");

        jButton1.setText("Iniciar sesión");

        jButton2.setText("Registrarte");

        jMenuPerros.setText("Perros");

        jMenuItemPerrosVer.setText("Ver");
        jMenuPerros.add(jMenuItemPerrosVer);

        jMenuItemPerrosAdoptar.setText("Adoptar");
        jMenuPerros.add(jMenuItemPerrosAdoptar);

        jMenuItemPerrosDarAdopcion.setText("Dar en adopción");
        jMenuPerros.add(jMenuItemPerrosDarAdopcion);

        jMenuBar1.add(jMenuPerros);

        jMenuGatos.setText("Gatos");

        jMenuItemGatosVer.setText("Ver");
        jMenuGatos.add(jMenuItemGatosVer);

        jMenuItemGatosAdoptar.setText("Adoptar");
        jMenuItemGatosAdoptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGatosAdoptarActionPerformed(evt);
            }
        });
        jMenuGatos.add(jMenuItemGatosAdoptar);

        jMenuItemDarAdopcion.setText("Dar en adopción");
        jMenuGatos.add(jMenuItemDarAdopcion);

        jMenuBar1.add(jMenuGatos);

        jMenuCuenta.setText("Cuenta");

        jMenuItemCuentaDatos.setText("Datos");
        jMenuCuenta.add(jMenuItemCuentaDatos);

        jMenuBar1.add(jMenuCuenta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelBienvenida2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelBienvenida)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelBienvenida1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(160, 160, 160))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabelBienvenida2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBienvenida1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton2))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGatosAdoptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGatosAdoptarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemGatosAdoptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelBienvenida;
    private javax.swing.JLabel jLabelBienvenida1;
    private javax.swing.JLabel jLabelBienvenida2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCuenta;
    private javax.swing.JMenu jMenuGatos;
    private javax.swing.JMenuItem jMenuItemCuentaDatos;
    private javax.swing.JMenuItem jMenuItemDarAdopcion;
    private javax.swing.JMenuItem jMenuItemGatosAdoptar;
    private javax.swing.JMenuItem jMenuItemGatosVer;
    private javax.swing.JMenuItem jMenuItemPerrosAdoptar;
    private javax.swing.JMenuItem jMenuItemPerrosDarAdopcion;
    private javax.swing.JMenuItem jMenuItemPerrosVer;
    private javax.swing.JMenu jMenuPerros;
    // End of variables declaration//GEN-END:variables
}
